### ISSUE TITLE
No dimming available?

### ISSUE THREAD

**Issue by larsenglund** [JeffResc/Sonoff-D1-Dimmer#7]
Hi, I just flashed the d1_dimmer_no_rf.h and the light shows up in home assistant but only as a ON/OFF light, not with dimming..
It does however dim on and off with a 1s transition when I toggle it so the dimming is there I just can't control it from home assistant. What did I do wrong?

**Comment by JeffResc** [comment]
This is the exact file I use personally and I have not had this issue. Please link to the exact file (version) that you are using for `d1_dimmer_no_rf.h`, and also please let me know the version of ESPHome you are using as well as the version of Home Assistant and I'll do my best to try and diagnose this issue.

**Comment by JeffResc** [comment]
Also, this may seem obvious, but I just want to double-check. You don't have `default_transition_length` set to `0s`, correct?

**Comment by larsenglund** [comment]
Hi, thanks for the reply! I didn't know which version I used but I updated everything to the latest version and reflashed and now the dimming works! So I guess it might have been an issue with old versions or something in homeassistant that was resolved with updating and restarting.
